### ISSUE TITLE
From where to get checkpoints please?

### ISSUE THREAD

**Issue by ramkumarkoppu** [MarkFzp/act-plus-plus#1]
Hi,

From where to get checkpoints please? `--ckpt_dir <ckpt dir>`

**Comment by SherwinDengxiong** [comment]
Based on the act project https://github.com/tonyzhaozh/act , You will get a checkpoint after you train the policy for one task.

**Comment by ramkumarkoppu** [comment]
Cheers

**Comment by skyuuarch** [comment]
测试评论
