### ISSUE TITLE
Load provided demo data

### ISSUE THREAD

**Issue by WangKeAlchemist** [MarkFzp/act-plus-plus#13]
Hi after realizing that data generated by script is mostly fail #12 , i use the demo data provided by the author. However I ran into data loading error when running the 'sim_transfer_cube_scripted' task. But you can remove 'left_wrist' and 'right_wrist' at https://github.com/MarkFzp/act-plus-plus/blob/main/constants.py#L11 and data can load successfully. Hope that helps :)

**Comment by tonyzhaozh** [comment]
Yes. We are also in-progress solving the data generation in this codebase. Please check out https://github.com/MarkFzp/act-plus-plus/issues/12 where I will try to share our progress debugging it.

Thanks,
Tony

**Comment by Ke-Wang1017** [comment]
Thanks!
