### ISSUE TITLE
Error: Visualize_episodes 

### ISSUE THREAD

**Issue by Doan-IT** [MarkFzp/act-plus-plus#16]
Hello. 
- Following the readme.txt instructions, I tried running visualize the episode:
python visualize_episodes.py --dataset_dir dataset/aloha_mobile_wipe_wine --episode_idx 10

- data save dir: download "aloha_mobile_wipe_wine" from google drive. (episode_0.hdf5 - to episode_49.hdf5)

- result: numpy.exceptions.AxisError:
all_cam_videos = np.concatenate(all_cam_videos, axis=2) # width dimension
numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2

Please support. Thanks a lot!

**Comment by lwcode** [comment]
meet the same problem

**Comment by tonyzhaozh** [comment]
Sorry for the confusion: the visualize script here is used for the legacy sim envs. Please use this https://github.com/MarkFzp/mobile-aloha/blob/main/aloha_scripts/visualize_episodes.py instead.
