### ISSUE TITLE
detr forward 

### ISSUE THREAD

**Issue by zf6578** [MarkFzp/act-plus-plus#17]
![image](https://github.com/MarkFzp/act-plus-plus/assets/26473502/dcb1125d-c353-41cd-80ec-9896edb8c2dd)
![image](https://github.com/MarkFzp/act-plus-plus/assets/26473502/d4bc8744-79bc-4bd7-a1ec-c49fb80dbd20)
parameter of forward is not match, as fig

**Comment by RyanJiao** [comment]
Hi, I would like to ask how is this solved?
