### ISSUE TITLE
How to ensure that the episode_len value remains unchanged when collecting data from multiple episodes of a task?

### ISSUE THREAD

**Issue by niovl** [MarkFzp/act-plus-plus#42]
For example, in task ```aloha_mobile_wash_pan```: in 50 episodes, ```episode_len=1099```. How to ensure that the length of the episodes remains unchanged? Are there some requirements for the teacher's operation, or are the collection results truncated? Hope to receive your answer, thx.

**Comment by asasarkaya** [comment]
Hi, I was wondering about the same question. Did you figure this out?

**Comment by niovl** [comment]
> Hi, I was wondering about the same question. Did you figure this out?

https://github.com/MarkFzp/act-plus-plus/blob/main/truncate_data.py，maybe it can help you
