### ISSUE TITLE
TypeError: forward() get an unexpected keyword argument 'pos'

### ISSUE THREAD

**Issue by WangKeAlchemist** [MarkFzp/act-plus-plus#5]
managed to load data but has error as the title
![Screenshot from 2024-01-04 11-12-50](https://github.com/MarkFzp/act-plus-plus/assets/8899545/b21a7528-42d1-47a3-9d93-34dff8b95006)

**Comment by apirrone** [comment]
I have the exact same issue. I'm digging into the code and will report back here if I find something :)

**Comment by apirrone** [comment]
Doing this https://github.com/MarkFzp/act-plus-plus/issues/3#issuecomment-1877316563 seems to solve the problem

**Comment by WangKeAlchemist** [comment]
yep as mentioned by @apirrone , in detr/models/detr_vae.py at line 285 change build_transformer to build_encoder will solve the issue and mine starts to train now
