### ISSUE TITLE
How to change camera resolution

### ISSUE THREAD

**Issue by yg1031** [MarkFzp/act-plus-plus#54]
Thanks for your great work!
I want to change camera resolution, I search the code and find definitions of cameras in assets/scene.xml, but there is no resolution defined.
Could you explain how to change camera resolution, thanks.

=========================================================
Solved:
1. ee_sim_env.py, change line:
```
obs['images']['top'] = physics.render(height=720, width=1280, camera_id='top')
```
2. assets/scene.xml, add line:
```
<visual>
    <global offwidth="1280" offheight="720"/>
</visual>
```

**Comment by hemangjoshi37a** [comment]
have you found any solution to this ? please help me
