### ISSUE TITLE
Whats's the reason to have two repos for the same project?

### ISSUE THREAD

**Issue by ramkumarkoppu** [MarkFzp/act-plus-plus#6]
Hi,

Whats's the reason to have two repos for the same project? :

https://github.com/MarkFzp/act-plus-plus
and 
https://github.com/tonyzhaozh/act

**Comment by auxon** [comment]
"Mobile ALOHA" expands on top of the original ALOHA project.

**Comment by tonyzhaozh** [comment]
act-plus-plus is a fork of act, that supports training with data from our new mobile-aloha hardware. It also has better implementation in general, see utils.py and imitate_episodes.py
