### ISSUE TITLE
About actions in record_episodes and imitate_episode

### ISSUE THREAD

**Issue by Cryon233** [MarkFzp/act-plus-plus#62]
Hi, I'm trying to apply the ACT algorithm to other robotic arms
I have a question as to why the action dimension of the dataset produced by record_sim__episodes.py is 14, but the action dimension of imitate_episode.py via load_data is 16
I noticed that the EpisodicDataset class created by load_data and get_norm_stats() added dummy_base_action to the action(padding two zeros after the action) causing this phenomenon, and I wondered why
![image](https://github.com/user-attachments/assets/9b80b374-22c9-411b-a1dd-12af85a3fbb5)
![image](https://github.com/user-attachments/assets/cf219625-4b85-4032-98bc-4622fecc5b62)
![image](https://github.com/user-attachments/assets/a2849281-ab46-4870-b485-2dd30fa5ef1f)
Thanks for a job well done!

**Comment by TomWangzs** [comment]
Since this is a mobile bimanual robot, in addition to the 14-dimensional arm position parameters, two additional dimensions for the base position parameters are also required.

**Comment by Cryon233** [comment]
> 由于这是一款移动式双手动机器人，因此除了 14 维手臂位置参数外，还需要两个额外的基本位置参数维度。

Thanks very much!
