### ISSUE TITLE
Not very good performance

### ISSUE THREAD

**Issue by WangKeAlchemist** [MarkFzp/act-plus-plus#8]
Hi I followed the instructions and trained the act policy for relatively long time (around 6 hours and 50k steps) and the success rate does not seem to be great. I have checked the tuning tips and plan to train for longer. However just want to know what can make the performance better? One issue i discover is that the scripted demo are mostly unsuccessful (just 30% success) and that is one potential problem, but are there other factors?
I post the wandb plot below 
 
![Screenshot from 2024-01-05 15-06-30](https://github.com/MarkFzp/act-plus-plus/assets/8899545/4d8cf7f9-2f1e-464f-8957-e15b99bb5bd5)

**Comment by tonyzhaozh** [comment]
Hi, as you might have noticed from other issues this is a dataset generation problem. We are trying to fix it and please check out https://github.com/MarkFzp/act-plus-plus/issues/12 for updates. I am closing this issue due to duplicates.

Thanks,
Tony
